### PR TITLE
Merge nodejs/master to xplat

### PR DESCRIPTION
**Pull request by kunalspathak**
Merge e8f3163 as of 2017-04-25. 

Only commit to review is 7fc3f3bebc3598f00e5c6a2a045bd029ab135973 where i fixed some unit test and marked some of the failing ones as FLAKY. This is to align with @joaocgreis work in https://github.com/nodejs/node-chakracore/pull/233.

Here are the details for unit test that are marked FLAKY.

* test-buffer-bindingobj-no-zerofill : This test is going to infinite loop
and timing out. It expects the allocateUnsafe should return non-zero filled
memory but node-chakracore always return buffer with zero filled.

* test-regress-GH-12371 : This one crashing with
`jsrt::Fatal("v8::ToLocalChecked: %s", "Empty MaybeLocal.");`.

* test-util : Expecting `isNativeError()` returns false for
`Object.create(Error.prototype)`

* test-zlib-convenience-methods : Getting this assert
` Assertion Buffer::IsWithinBounds(in_off, in_len, Buffer::Length(in_buf))' failed`

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-guidelines)

##### Affected core subsystem(s)

core, test

### CODE REVIEW

**Comment by kunalspathak** [comment]
cc: @nodejs/node-chakracore 

CI : https://ci.nodejs.org/view/All/job/chakracore-test-pull-request/14/

**Comment by jasongin** [comment]
> Merge nodejs/master to xplat

Is this merging from the `master` branch or `v8.x` branch of `nodejs/node`?

**Comment by kunalspathak** [comment]
@jasongin  - From `master` branch of `nodejs/node` and that's why is targeted for `xplat`.

**Review by kfarnung — APPROVED** [review]
LGTM

**Pull request merged**
