### PR TITLE
chakrashim: enable IdleGC on cross platform

### PR DESCRIPTION
**Pull request by obastemur**
Enables ChakraCore IdleCollect on non-Windows platforms.

### CODE REVIEW

**Comment by obastemur** [comment]
See https://github.com/Microsoft/ChakraCore/pull/2988

**Comment by obastemur** [comment]
Enabling IdleGC helps with the memory consumption when the process is Idle.

**Comment by kunalspathak** [comment]
:shipit:

**Comment by kunalspathak** [comment]
Curious, how much win we get with this on x-plat? Didn't realize that IdleGc is disabled for xplat.

**Review by kfarnung — APPROVED** [review]
🚢

**Pull request closed without merging**
