### PR TITLE
V8.6.0 proposal

### PR DESCRIPTION
**Pull request by MSLaguana**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by MSLaguana** [comment]
CI run: https://ci.nodejs.org/job/chakracore-test-pull-request/153/

**Comment by MSLaguana** [comment]
This is still on the chakracore 1.7.2 release, and needs to be updated with the latest from there once we pick a cutoff.

**Comment by MSLaguana** [comment]
CI is ~green, for our values of green. There is one remaining lint failure, but that exists in node's v8.6.0 tag, and there's an upstream fix checked into master for it. Our xplat CI is only failing due to lingering processes which we expect. What I'm not sure about is why our windows CI is hanging on one test, and I don't know how to work out what test is hanging because it doesn't print that out until after it's done.

**Comment by digitalinfinity** [comment]
@joaocgreis do you have any experience dealing with test hangs in the CI on Windows? Is the best option to get access to the machine, hop on and see what process is still around? @MSLaguana I'm assuming you can't reproduce the hanging test locally, yes?

**Comment by joaocgreis** [comment]
The test that is hanging is `inspector/test-contexts`. It can be run directly with:
```
Release\node.exe --expose-gc test\inspector\test-contexts.js
```
or using the test runner:
```
python tools\test.py inspector/test-contexts
```

This hangs every time, both in the CI machine and locally in my machine.

**Comment by MSLaguana** [comment]
Ah, we hit that in master branch and I had missed that commit.

**Comment by joaocgreis** [comment]
@MSLaguana is the test expected to never work with ChakraCore or is it a failure that has yet to be investigated? If the test is expected to work some time in the future, it should be marked as flaky in the status file instead (ref https://github.com/nodejs/node-chakracore/pull/233).

**Comment by MSLaguana** [comment]
It's something that we'd like to work in future, but needs some additional capabilities added before we get there. We did start by marking it as flaky in the status file... however that doesn't stop it from hanging forever as you see here.

**Comment by joaocgreis** [comment]
Good point, flaky is not enough when the test runner breaks. There's also the option of marking as `SKIP` (like https://github.com/nodejs/node-chakracore/commit/db752808343f070fb5db0bcb221683e346f01ec1 - which never landed because the test was fixed while the PR was open).

**Comment by digitalinfinity** [comment]
thanks for your help @joaocgreis!

**Pull request merged**
