### PR TITLE
Sync to nodejs/master (2016-05-29)

### PR DESCRIPTION
**Pull request by kunalspathak**
##### Checklist

- [x] tests and code linting passes
- [x] the commit message follows commit guidelines
##### Affected core subsystem(s)

deps, test
##### Description of change

Sync nodejs/master at 112b9cd as of 2016-05-29

### CODE REVIEW

**Comment by jianchun** [comment]
LGTM

**Comment by alexlamsl** [comment]
OT: should we be expecting binaries for `pre8` soon?

**Comment by kunalspathak** [comment]
@alexlamsl , I will be porting [chakracore 1.2](https://github.com/Microsoft/ChakraCore/tree/release/1.2) in next few weeks after which we will release `pre8`.

**Comment by jianchun** [comment]
@kunalspathak Just wondering what if you turn off experimental features completely here? Previously we need it for one feature which might be on by default now.

**Comment by kunalspathak** [comment]
Yeah, do you recall for which feature we added experimental in first place? Note that we will still need changes in core to enable/disable SIMD feature because there is unit test that does verify with `--harmony-simd`.

Thanks,
Kunal

**Comment by jianchun** [comment]
> do you recall for which feature we added experimental in first place?

Seems to be function generator.

> Note that we will still need changes in core to enable/disable SIMD feature because there is unit test that does verify with `--harmony-simd`.

Right... But if number of failures are small, it may be a possibility to not make this temporary JSRT change right now.

**Comment by kunalspathak** [comment]
There are some `ES6` features like `ES6Unscopable` that jslint depends on and if we don't send experimental flag, jslint stops working. There are also some unit test failures because of "defaults in formals" feature that is under experimental.

**Comment by jianchun** [comment]
Great to know, thanks for looking!

**Pull request merged**
