### PR TITLE
test: fixing line endings

### PR DESCRIPTION
**Pull request by kfarnung**
The line endings were CRLF in the repo, causing failures on Linux.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

test

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/144/

**Comment by kfarnung** [comment]
The CI looks green for the linter now.

**Review by boingoing — APPROVED** [review]

**Review by jackhorton — APPROVED** [review]

**Comment by boingoing** [comment]
@kfarnung I made the same fix as part of #381 which landed via 3e706ba35d. I'm going to close this PR since the change has made it in. 👍

**Comment by kfarnung** [comment]
Thanks @boingoing!

**Pull request closed without merging**
