### PR TITLE
Fix for build break in PR #194.

### PR DESCRIPTION
**Pull request by mrkmarron**
- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] documentation is changed or added

##### Description of change
Fix for build break in PR #194 -- issue #https://github.com/nodejs/node-chakracore/issues/195

PR-URL: https://github.com/mrkmarron/node-chakracore/commit/fafa1551df6327d7ee52863efe4757faf0c1d50a

### CODE REVIEW

**Comment by digitalinfinity** [comment]
LGTM. Why is this a problem only in Ubuntu and not Windows/macOs?

CI is at https://ci.nodejs.org/view/All/job/chakracore-test-windows/

**Comment by digitalinfinity** [comment]
@kunalspathak @joaocgreis Did I trigger the CI incorrectly? I see failures here that cor.h is not available while compiling ChakraCore- https://ci.nodejs.org/job/node-compile-windows/label=win-vcbt2015/7765/console

**Comment by kunalspathak** [comment]
vcbt flavor is expected to fail. There was an issue opened by @joaocgreis , but I can't find it right now. As long as other flavors pass, it should be good. Also, the CI doesn't have Ubuntu verification and this fix needs Ubuntu testing. At this point, I would just manually make sure that there are no build/test failures on Ubuntu with this Pr.

**Comment by joaocgreis** [comment]
Reopened VCBT issue: https://github.com/nodejs/node-chakracore/issues/200 (user account that was used to upen it was deleted, and GitHub silently deleted the issue as well).

**Pull request merged**
