### PR TITLE
node.gypi: fix osx build

### PR DESCRIPTION
**Pull request by obastemur**
update chakrashim build condition to latest changes.

### CODE REVIEW

**Review by digitalinfinity — APPROVED** [review]

**Comment by jackhorton** [comment]
What is the actual fix here? It says --force-load is not applicable to a static library in the comment, so why is "target_type != static" any different than "force_load == true" ?

**Comment by digitalinfinity** [comment]
I interpreted it as earlier, they would set `-forceload` if it wasn't a static library- now there is an explicit configuration flag indicating whether we want that flag to be passed in or not.

**Comment by kfarnung** [comment]
Could we (should we?) upstream this change?

**Review by kfarnung — APPROVED** [review]

**Comment by obastemur** [comment]
merged https://github.com/nodejs/node-chakracore/commit/f881539b101f027538ee11dce153d458ff84af03

**Comment by obastemur** [comment]
> Could we (should we?) upstream this change?

Upstream doesn't have that part in node.gypi

**Pull request closed without merging**
