### PR TITLE
10.9.0 proposal

### PR DESCRIPTION
**Pull request by kfarnung**
Merged upstream tag v10.9.0 into v10.x

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/302/

**Comment by kfarnung** [comment]
@digitalinfinity @MSLaguana Please take a look at ~~https://github.com/nodejs/node-chakracore/pull/583/commits/3e41263cc2b634b8989a41e3c9143f937b56bb26~~ https://github.com/nodejs/node-chakracore/pull/583/commits/e7c7eafabc4b2739bff2535e5f4afc9e88180c22

EDIT: I used BeyondCompare to diff the Win32 and WOA definitions.  I think since there are no changes in the diff which mention WIN32 or revert WOA, I think it's fine.

**Comment by kfarnung** [comment]
New CI: https://ci.nodejs.org/job/chakracore-test-pull-request/304/

**Comment by MSLaguana** [comment]
I took a look, nothing seemed particularly crazy so if it builds then LGTM

**Review by MSLaguana — APPROVED** [review]

**Pull request merged**
