### PR TITLE
master branch cleanup

### PR DESCRIPTION
**Pull request by kfarnung**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Affected core subsystem(s)

chakrashim, src, test

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/191/

**Comment by kfarnung** [comment]
I'll rebase this on #465 once that lands.

**Review by boingoing — APPROVED** [review]
LGTM

**Review by digitalinfinity — APPROVED** [review]

**Comment by kfarnung** [comment]
New CI: ~~https://ci.nodejs.org/job/chakracore-test-pull-request/192/~~
https://ci.nodejs.org/job/chakracore-test-pull-request/193/

**Pull request merged**
