### PR TITLE
Merge nodejs/node master

### PR DESCRIPTION
**Pull request by kunalspathak**
Merge commit 260cd411d4 as of 2017-05-24

Interested commit to review:
* a96913260a8abc6bc8cce530062b18268ad09a66 -  test: Fixed some failing unit test after merge

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

core, test

### CODE REVIEW

**Comment by jasongin** [comment]
In https://github.com/nodejs/node-chakracore/pull/264/commits/a96913260a8abc6bc8cce530062b18268ad09a66, can you explain "test was failing because of over specifiying a not condition"?

And is this failure from a new test that was added with the merge, or a test that was already existing (and previously passing) in Node-ChakraCore?

**Comment by kunalspathak** [comment]
@jasongin  - The failure came when new coverage was added in https://github.com/nodejs/node/commit/47919b3b6f1592ce80ec3c07b0eaea64c1d7e4dc . The bug was in [this](https://github.com/nodejs/node-chakracore/blob/xplat/src/node_api_jsrt.cc#L574) line. The condition should be just `if ((properties[i].attributes & napi_static) != 0) `

**Comment by jasongin** [comment]
OK thanks. That looks fine then. Though for clarity, the component prefix on that commit message should probably be `n-api`, not `test`. I think the guidance is that the `test` prefix is when only test code is changed.

**Review by jasongin — APPROVED** [review]

**Comment by kunalspathak** [comment]
Yes, i think i will just separate out that change in a different commit when i merge.

**Comment by kfarnung** [comment]
Should https://github.com/nodejs/node-chakracore/commit/a96913260a8abc6bc8cce530062b18268ad09a66 also have "src" in the tags?

**Review by kfarnung — APPROVED** [review]

**Comment by kunalspathak** [comment]
Thanks @kfarnung  and @jasongin  for the review.

**Comment by kunalspathak** [comment]
CI - ~https://ci.nodejs.org/job/chakracore-test-pull-request/54/console~ 
https://ci.nodejs.org/job/chakracore-test-pull-request/55/

**Pull request merged**
