### PR TITLE
napi_jsrt: implement promise

### PR DESCRIPTION
**Pull request by gabrielschulhof**
##### Checklist

- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

n-api

### CODE REVIEW

**Review by boingoing — APPROVED** [review]
LGTM 👍

**Comment by kfarnung** [comment]
@gabrielschulhof Are the other files from your upstream change?  We should ideally wait for the pump to merge them, then take the JSRT changes in.  @boingoing can help coordinate that.

**Review by kfarnung — APPROVED** [review]
LGTM, but let's make sure the upstream change is merged first and then rebase against it.

**Comment by gabrielschulhof** [comment]
Before submitting the PR I manually pulled nodejs/node master into my
branch to see what would happen, and there were no conflicts with any of
the files this PR touches.

**Comment by gabrielschulhof** [comment]
Of course it's prudent to let the bot do the pulling, because somebody
else may touch these files in the meantime.

**Comment by kfarnung** [comment]
Thanks @gabrielschulhof, that's what I figured.  @boingoing is already working on the merge to bring the upstream changes in and I think we have a plan in place to land this PR.  LGTM, so as soon as we have the branch ready we'll get this landed.

**Comment by boingoing** [comment]
@gabrielschulhof I rebased your branch on top of master after we took the upstream changes with the promise test. Let's do a sanity CI and then merge it in. 👍

CI:
https://ci.nodejs.org/job/chakracore-test/180/

**Comment by boingoing** [comment]
Pushed a commit to fix the linter failure in the CI - this was not your fault. New CI:
https://ci.nodejs.org/job/chakracore-test/182/

**Comment by boingoing** [comment]
Landed in 3e706ba35d.

Thanks, @gabrielschulhof!

**Pull request merged**
