### PR TITLE
Implement Isolate::SetPromiseRejectCallback

### PR DESCRIPTION
**Pull request by kfarnung**
I temporarily backported https://github.com/Microsoft/ChakraCore/commit/0b61d16afc28084673b29a768661b9a9689ff230 to https://github.com/kfarnung/ChakraCore/tree/promisereject for use in node-chakracore.

Assuming the node-chakracore changes look good we'll have to discuss how the Chakracore changes will flow into the branch.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Affected core subsystem(s)

chakrashim

### CODE REVIEW

**Comment by boingoing** [comment]
LGTM, are there tests for this we can enable?

**Review by boingoing — APPROVED** [review]

**Comment by kfarnung** [comment]
Opened the backport PR:  https://github.com/Microsoft/ChakraCore/pull/4697

**Comment by kfarnung** [comment]
@boingoing I'm currently investigating the obvious test cases.  Looks like a couple inspector testcases are now failing, I suspect they always were but without unhandled rejection support they weren't being reported.

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/195/

**Comment by kfarnung** [comment]
Re-run CI with x86 fixes:  https://ci.nodejs.org/job/chakracore-test-windows/316/

**Comment by kfarnung** [comment]
New CI: https://ci.nodejs.org/job/chakracore-test-pull-request/198/

**Review by MSLaguana — APPROVED** [review]

**Pull request merged**
