### PR TITLE
Merge nodejs/master into xplat

### PR DESCRIPTION
**Pull request by kfarnung**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

test

### CODE REVIEW

**Comment by digitalinfinity** [comment]
I think @kunalspathak prefers if the commit message for the merge commit matches the one he auto-generates. Other than that, LGTM

**Comment by kfarnung** [comment]
@digitalinfinity That's exactly why I think we should be scripting these conflict resolutions.

**Comment by kunalspathak** [comment]
I think you just need to remove the quotes around commit title although pump doesn't care about it. It is just good for readability to have something like :

Merge commit effeff1843 into xplat

Also, remove this part

```cmd
Conflicts:
  test/parallel/test-process-versions.js
```

**Review by kunalspathak — APPROVED** [review]

**Comment by kfarnung** [comment]
@kunalspathak I was following the pattern from 7aa5a91bacf14807f8e21c871f026b530c7f2a3b which left the conflicts part in.  I can remove it though.

**Comment by digitalinfinity** [comment]
Personally, I prefer leaving the conflict parts in to make it clear what files were touched in the merge commit itself- but that's just my opinion 😄

**Pull request merged**
