### PR TITLE
Merge nodejs/master 

### PR DESCRIPTION
**Pull request by kunalspathak**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

chakrashim, test

##### Description of change

Merge https://github.com/nodejs/node/commit/b32ae9e74dab25b905ef001638af7df77ca2d987 from nodejs/master

### CODE REVIEW

**Comment by kunalspathak** [comment]
CI : https://ci.nodejs.org/job/chakracore-test-windows/

**Comment by kunalspathak** [comment]
@digitalinfinity - Please help review!

**Comment by digitalinfinity** [comment]
Reviewed 83d2df3, 233a053 and ed2964b and they look good to me. Didn't review the merge commit since I assume it was trivial, but let me know if you think I should review that too. Otherwise, LGTM

**Comment by kunalspathak** [comment]
@digitalinfinity , i have taken another FI yesterday. Could you review last 2 commits?

CI : https://ci.nodejs.org/job/chakracore-test-windows/36/

**Review by kfarnung — APPROVED** [review]
LGTM 👍

**Pull request merged**
