### PR TITLE
Merge nodejs/node master

### PR DESCRIPTION
**Pull request by kunalspathak**
Merge 11918c4aed as of 2017-05-16. 

Interesting commits to review:
* f7b8a7b Build errors fix.

* a878d71 Fix N-API JSRT bugs found by new tests. @jasongin  helped fixed this. Despite fixing there are still 3 outstanding test failures in test-addons-napi. Jason will fix it, but it will be a while when the fix comes to node-chakracore. I have intentionally not skipping these tests.

* f43248f chakrashim, Build errors fix. There were several test cases related to promise and async that I had to mark flaky for now. 😞 

##### Checklist

- [ ] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-guidelines)

##### Affected core subsystem(s)

core, chakrashim, test

### CODE REVIEW

**Comment by kfarnung** [comment]
Just a nit for the new shims:

https://github.com/nodejs/node-chakracore/commit/f43248f1b6bef0eb10d8415ab0e5b502188ffbca#diff-913fb686e1d16cb72858e61d72d46b8cR998

The approach that seems to be standard in the codebase is that continuations from the previous line are indented to either:
* line up with the parameters on the previous line
* indent 4 spaces

**Review by kfarnung — APPROVED** [review]
LGTM with minor nits

**Comment by jasongin** [comment]
The `addons-napi/test_async` failure appears to be a chakrashim issue that just happens to have been uncovered by the test; it is not actually N-API-specific.

The problem seems to be that `node::EmitBeforeExit()` tries to allocate a string while in an exception state. `JsCreateString()` returns `JsErrorInExceptionState`, and that leads to a fatal error: "V8::ToLocalChecked: Empty MaybeLocal". Does `node::EmitBeforeExit()` need to clear the JSRT exception state before doing more work?

This test case is checking the behavior of an unhandled JS exception thrown from a libuv async callback. See `addons-napi/test_async/test.js:13`.

Here is the call stack where the error originated:
```
>	chakracore.dll!ContextAPINoScriptWrapper_Core<_JsErrorCode <lambda>(Js::ScriptContext *) >(ContextAPINoScriptWrapper::__l2::_JsErrorCode <lambda>(Js::ScriptContext *) fn, bool allowInObjectBeforeCollectCallback, bool scriptExceptionAllowed) Line 242	C++
 	chakracore.dll!ContextAPINoScriptWrapper<_JsErrorCode <lambda>(Js::ScriptContext *, TTD::TTDJsRTActionResultAutoRecorder &) >(JsPointerToString::__l2::_JsErrorCode <lambda>(Js::ScriptContext *, TTD::TTDJsRTActionResultAutoRecorder &) fn, bool allowInObjectBeforeCollectCallback, bool scriptExceptionAllowed) Line 291	C++
 	chakracore.dll!JsPointerToString(const wchar_t * stringValue, unsigned __int64 stringLength, void * * string) Line 1189	C++
 	chakracore.dll!JsCreateString(const char * content, unsigned __int64 length, void * * value) Line 4105	C++
 	node.exe!v8::String::NewFromOneByte(v8::Isolate * isolate, const unsigned char * data, v8::NewStringType type, int length) Line 218	C++
 	node.exe!node::OneByteString(v8::Isolate * isolate, const char * data, int length) Line 205	C++
 	node.exe!node::EmitBeforeExit(node::Environment * env) Line 4498	C++
 	node.exe!node::Start(v8::Isolate * isolate, void * isolate_context, int argc, const char * const * argv, int exec_argc, const char * const * exec_argv) Line 4639	C++
 	node.exe!node::Start(uv_loop_s * event_loop, int argc, const char * const * argv, int exec_argc, const char * const * exec_argv) Line 4732	C++
 	node.exe!node::Start(int argc, char * * argv) Line 4971	C++
 	node.exe!wmain(int argc, wchar_t * * wargv) Line 71	C++
```

**Comment by kunalspathak** [comment]
@jasongin - Thanks for looking. I will investigate and fix this one.

**Comment by kunalspathak** [comment]
Spoke offline with @jasongin . The problem is `GetAndClearException()`  today happens either when `Scope` is popped or in dtor of `v8::TryCatch`. The napi jsrt APIs has to implement `TryCatch` like model where it will throw unhandled exception and clear it from context.

**Comment by kunalspathak** [comment]
Rebased. CI - https://ci.nodejs.org/job/chakracore-test-pull-request/37/

**Comment by jasongin** [comment]
All the test failures are fixed here: https://github.com/jasongin/node-chakracore/commit/a32568a494784992a6fbc897fc503623d3634320

If you don't want to take that commit now, I'll submit it as a PR separately.

**Comment by kunalspathak** [comment]
Once my PR is merged, could you please send a separate PR? Also re-enable the test that i will be skipping in my PR.

**Comment by jasongin** [comment]
OK

**Comment by kunalspathak** [comment]
New CI - https://ci.nodejs.org/job/chakracore-test-pull-request/39/

**Pull request merged**
