### PR TITLE
Merge 'xplat' into xplat-v8.x

### PR DESCRIPTION
**Pull request by kfarnung**
Currently the v8.x upstream branch contains the most recent master commit.  This enables us to just merge xplat directly to v8.x and not bring over any changes that weren't planned to land in v8.x.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-guidelines)

### CODE REVIEW

**Comment by kfarnung** [comment]
This change makes the xplat-v8.x branch identical to the xplat branch.  CI will be scheduled once the Jenkins instance starts responding.

**Comment by agarwal-sandeep** [comment]
The last commit d251615 touches 3790 files, what was the criteria to revert unneeded changes?

**Review by kunalspathak — APPROVED** [review]
LGTM as long as CI is green.

**Comment by kfarnung** [comment]
CI:  https://ci.nodejs.org/job/chakracore-test-pull-request/16/

/cc @nodejs/node-chakracore

**Pull request merged**
