### PR TITLE
test: enable bigint tests on v8

### PR DESCRIPTION
**Pull request by kfarnung**
* Use eval to enable tests to run on v8 and chakracore
* Clean up status files
* Fix a lint issue

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Review by MSLaguana — APPROVED** [review]

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/315/

**Comment by IrinaYatsenko** [comment]
Isn't it useful to run the tests for non-bigInt cases? I did it for the pump in d4d1ef76f7. I'm fine with eval as well, but it likely will be a conflict.

**Comment by kfarnung** [comment]
I'm assuming these cases are covered elsewhere, these are specifically about testing bigint.  This is based on the current master, so there should be no conflict.

**Comment by kfarnung** [comment]
CI rerun: https://ci.nodejs.org/job/chakracore-test-pull-request/316/

**Comment by IrinaYatsenko** [comment]
If I understand it correctly, the tests validate equivalence of various types when used as keys/values (e.g. null and undefined). BigInts were added as yet another equivalence test.

**Comment by kfarnung** [comment]
Correct, but if we don't support bigints then the test isn't necessary for node-chakracore anyway.

**Comment by IrinaYatsenko** [comment]
Aren't you disabling the tests for undefined, null and falsies (as well as bigInt)? I don't like it that all of them are in the same bucket, should probably be separate (that, or I don't understand the tests).

**Comment by kfarnung** [comment]
Oh, I see now, it looks like they conflated these tests a bit.  I think I'd rather just disable them rather than trying to duplicate their behavior without BigInt.  That will keep merge conflicts to a minimum in the future.

**Comment by IrinaYatsenko** [comment]
OK. I'm fine with that.

**Review by IrinaYatsenko — APPROVED** [review]

**Comment by joaocgreis** [comment]
Rebuild of the Windows job: https://ci.nodejs.org/job/chakracore-test-windows/492/ (failed in the test-PR above for unrelated reasons).

**Review by sethbrenith — APPROVED** [review]
:shipit:

**Pull request merged**
