### PR TITLE
test: update `areAllValuesEqual` to use strings

### PR DESCRIPTION
**Pull request by kfarnung**
This allows it to compare regular expressions as well.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

test

### CODE REVIEW

**Comment by MSLaguana** [comment]
How is this function used? By stringifying everything, it will make `{}` and `{foo:1}` be equal, because they will become `"[object Object]"`. The way it is originally, using `!==` suggests that it is intending to test exact (in)equality.

**Comment by kfarnung** [comment]
It's only used by `engineSpecificMessage` which should only get strings and regexps passed into it. I was originally just checking exact equality which means that regular expressions would never be equal.

I can rename the method or add some type checking to detect bad usages.

**Review by kunalspathak — APPROVED** [review]

**Comment by kfarnung** [comment]
@MSLaguana does the latest iteration address your feedback?

**Review by MSLaguana — APPROVED** [review]
Looks fine to me if that's the use-case.

**Pull request merged**
