### PR TITLE
Merge fe730d3 as of 2017-07-03

### PR DESCRIPTION
**Pull request by kfarnung**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

chakrashim

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/99/

**Comment by MSLaguana** [comment]
Looks like CI linter is angry:
```
Running C++ linter...
src/node_api_jsrt.cc:587:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
Total errors found: 1
```

**Comment by kfarnung** [comment]
@MSLaguana I took your change from https://github.com/nodejs/node/pull/14111 as well.

**Comment by kfarnung** [comment]
New CI: https://ci.nodejs.org/job/chakracore-test-pull-request/100/

**Comment by kfarnung** [comment]
CI looks good

**Review by MSLaguana — APPROVED** [review]

**Pull request merged**
