### PR TITLE
Updating cctest EnvironmentTestFixture to use context::Scope

### LINKED ISSUE #529: cctest test_platform.cc fails on node-chakracore
* **Version**: Commit d3edf2fcde0c37206dc339aab7333212d20aa0f1
* **Platform**: Windows
* **Subsystem**: Test

The new cctest.exe test in `test_platform.cc` fails on node-chakracore due there being no context when we try to create a string:

```
[----------] 1 test from PlatformTest
[ RUN      ] PlatformTest.SkipNewTasksInFlushForegroundTasks
FATAL ERROR: v8::ToLocalChecked: Empty MaybeLocal.
Important: While trying to check Javascript exception, JsHasException has also failed.
```

Adding a `v8::Context::Scope` to `SkipNewTasksInFlushForegroundTasks` which either reuses `env.context()` or creates a new context from the isolate causes the test to fail with a SEH exception:

```
[----------] 1 test from PlatformTest                                                                                                         
[ RUN      ] PlatformTest.SkipNewTasksInFlushForegroundTasks                                                                                  
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.                                                              
[  FAILED  ] PlatformTest.SkipNewTasksInFlushForegroundTasks (8 ms)                                                                           
cmd - cctest.exe[26076]: e:\node\node-chakracore\test\cctest\node_test_fixture.h:84: Assertion `(0) == (uv_loop_close(&current_loop))' failed.
 1: node::Abort                                                                                                                               
 2: node::Assert                                                                                                                              
 3: NodeTestFixture::TearDownTestCase                                                                                                         
 4: testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test,void>                                                             
 5: testing::TestCase::Run                                                                                                                    
 6: testing::internal::UnitTestImpl::RunAllTests                                                                                              
 7: testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl,bool>                                           
 8: main                                                                                                                                      
 9: __scrt_common_main_seh                                                                                                                    
10: BaseThreadInitThunk                                                                                                                       
11: RtlUserThreadStart                                                                                                                        
```

I disabled this test for now until we can solve the context issue.

### PR DESCRIPTION
**Pull request by MSLaguana**
Fixes #529

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by MSLaguana** [comment]
I'm checking to see if this also fixes the environment tests, if so I'll update the PR.

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/248/

**Comment by MSLaguana** [comment]
Updated CI: https://ci.nodejs.org/job/chakracore-test-pull-request/250/

**Comment by MSLaguana** [comment]
CI is looking OK so far; windows failed on one instance due to git-related issues.

**Review by boingoing — APPROVED** [review]

**Comment by MSLaguana** [comment]
Landed as d661a66851

**Pull request closed without merging**
