### PR TITLE
2016-04-01, node-chakracore-6.0.0-pre6

### PR DESCRIPTION
**Pull request by jianchun**
Added initial deps/chakrashim/CHANGELOG.md.
Added update-changelog.js script.

This is for #48.

@nodejs/node-chakracore Please review. Thanks!

### CODE REVIEW

**Comment by jianchun** [comment]
Sorry, please hold on. The .md file does not look right on GitHub. Looking.

**Comment by MylesBorins** [comment]
@jianchun you may want to take a look at https://github.com/rvagg/changelog-maker which is what we use for generating our change logs. Simply putting the sha's are not going to generate links on github until the sha exists in the repo, since this PR is coming from a personal branch it can't do that yet.

We end up putting the full link + the sha in our changelogs to be explicit... but that is all generated by the tool. Examples of using it can be found in our [releases.md](https://github.com/nodejs/node/blob/master/doc/releases.md)

**Comment by jianchun** [comment]
@TheAlphaNerd Thanks for the info and the pointer! I searched for an existing maker the other day but didn't find this one. I ended up writing my own because we did non-standard things previously in the repo history (rewriting history, tagging different branches), we are not using expected sem-version (as we are a sub-project), and I wanted this CHANGELOG.md to reside in a subfolder and filter the change logs to primarily for the subfolder. I'll try to use full link.

**Comment by jianchun** [comment]
Now hardcoded commit URL. Please review. Thanks!

**Comment by agarwal-sandeep** [comment]
Looks good to me

**Comment by jianchun** [comment]
We just found Windows ARM build was broken. Fixed together with Sandeep. @agarwal-sandeep Could you please double verify the fix here is good? Thanks!

**Pull request merged**
