### PR TITLE
Merge nodejs/master into xplat

### PR DESCRIPTION
**Pull request by kfarnung**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines][]

##### Affected core subsystem(s)

chakrashim,lib,test

[commit guidelines]: https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-guidelines

### CODE REVIEW

**Comment by kfarnung** [comment]
CI:  https://ci.nodejs.org/job/chakracore-test-windows/52/

**Review by kunalspathak — APPROVED** [review]

**Comment by kfarnung** [comment]
CI retry:  https://ci.nodejs.org/job/chakracore-test-windows/53/

**Comment by kunalspathak** [comment]
LGTM

**Review by kunalspathak — APPROVED** [review]

**Comment by kfarnung** [comment]
CI retry: https://ci.nodejs.org/job/chakracore-test-windows/54/

**Comment by kfarnung** [comment]
CI seems unstable, three CIs with completely different failures.  The last retry failed to start running the tests on one machine.  For machines that ran, all tests passed.

**Comment by digitalinfinity** [comment]
@joaocgreis is the instability in the CI expected?

**Comment by joaocgreis** [comment]
The two tests that failed are flaky, they did not fail in other runs.

Tests failing to start happens from time to time, on all platforms, usually with a `remote file operation failed` or `connection closed` message (https://github.com/nodejs/build/issues/173). This one was a little different, but the slave did not fail again so it might have been a temporary git network failure. Any how, that test subset was green on previous runs, so it was safe to land.

**Pull request merged**
