### PR TITLE
tools: update dependencies in tools/doc  …

### PR DESCRIPTION
**Pull request by Trott**
This clears warnings from `npm audit`.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/chakracore Other than bot-commits to update Chakracore, this repo hasn't seen any movement since February. Is this still a going concern? If so, cool. But if not, I guess I should close this?

**Comment by joaocgreis** [comment]
@Trott shouldn't this change come from a merge with the main repo? Those used to happen quite frequently, but it looks like no one was able to do one for a while. Are the `npm audit` warnings causing pain somewhere?

**Comment by Trott** [comment]
> @Trott shouldn't this change come from a merge with the main repo?

Ideally, yes. 

> Those used to happen quite frequently, but it looks like no one was able to do one for a while. Are the `npm audit` warnings causing pain somewhere?

Probably not. I try to go through the `nodejs` repos from time to time and clean them up. Feel free to close-and-ignore if that's the best thing to do.

**Comment by joaocgreis** [comment]
This will probably be overwritten when the main repo is merged, but until then there's no harm landing this. Thanks @Trott!

CI: https://ci.nodejs.org/view/All/job/chakracore-test-pull-request/328/
master CI: https://ci.nodejs.org/view/All/job/chakracore-test/437/
Clearly needs a lot of attention to mean something again.

**Pull request merged**
