### PR TITLE
deps: allow openssl to build for WOA

### PR DESCRIPTION
**Pull request by kfarnung**
Add definitions to enable building for Windows on ARM

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/235/

**Comment by kfarnung** [comment]
New CI for vcbuild change:  https://ci.nodejs.org/job/chakracore-test/312/

**Comment by digitalinfinity** [comment]
Is this my change more or less verbatim or are there particular changes you'd like me to review? If not, LGTM 😄

**Comment by kfarnung** [comment]
It's just your change with the patch for vcbuild.bat.  I believe the build machines in the CI have NASM installed so it again went down the Linux path.

**Comment by kfarnung** [comment]
Looks like the ARM build is good now:  https://ci.nodejs.org/job/node-compile-windows/17473/label=win-vs2017-arm/

**Comment by digitalinfinity** [comment]
Ah lol! I wondered about that but assumed that the config script would have automatically switched to using the asm disabled version. Ok, LGTM- thanks for adopting!

**Review by MSLaguana — APPROVED** [review]

**Pull request merged**
