### PR TITLE
Xplat merge

### PR DESCRIPTION
**Pull request by ianwjhalliday**
Merge nodejs/node@4d3b487b791606ea965f6280ce0eeea03d79b660 into node-chakracore/xplat

Fix build issues and minor test issues as result of merge.

Skip new test failure for TypedArray .length property override in test/parallel/test-buffer-fill.js that is due to ChakraCore JIT bug.

Do not call weak persistent callback for ObjectBeforeCollectCallback when IsolateShim is Disposing.  This was a bug that led to AsyncWrap destructors accessing node::Environment after it was out of scope.

### CODE REVIEW

**Comment by ianwjhalliday** [comment]
@digitalinfinity @jianchun @kunalspathak @kfarnung fyi and please review as appropriate

**Comment by kunalspathak** [comment]
Triggered CI - https://ci.nodejs.org/view/All/job/chakracore-test-windows/31/

**Comment by agarwal-sandeep** [comment]
deps\chakrashim\include\v8.h have tabs instead of space at multiple places in new code. Please run tools\cpplint.py on all changed .cc and .h files and make sure no new warnings are introduced.

**Comment by agarwal-sandeep** [comment]
Do we have an issue opened to implement/fix ShouldThrowOnError?

**Comment by agarwal-sandeep** [comment]
in commit ba8b5e78e0e8c0e709d4231da9abfa668b082a4d (node.cc) LF is replaced with CRLF

**Comment by jianchun** [comment]
Weak persistent callback change looks good to me.

**Comment by kfarnung** [comment]
Tried out TTD (patched with the core fixes), everything LGTM.

**Comment by kunalspathak** [comment]
@ianwjhalliday - there are failures in CI unit test for windows. Can you fix it?

https://ci.nodejs.org/job/node-test-binary-windows/5814/

**Comment by ianwjhalliday** [comment]
I believe I have addressed the test failure and all the feedback.

Created #168 to track `ShouldThrowOnError` TODO.

Running CI again here https://ci.nodejs.org/view/All/job/chakracore-test-windows/32/

@agarwal-sandeep look good?

**Comment by ianwjhalliday** [comment]
Accidentally hit the `Close and comment` button -_-;;

**Comment by agarwal-sandeep** [comment]
node.cc still contains CRLF, I think we should fix that. Rest looks good to me if CI is all green.

**Comment by ianwjhalliday** [comment]
Fixed the CRLFs properly this time and merged the PR.

**Comment by kunalspathak** [comment]
@ianwjhalliday , not sure if you checked this but 1 test case in CI failed 
https://ci.nodejs.org/job/node-test-binary-windows/RUN_SUBSET=0,VS_VERSION=vs2013,label=win2008r2/5880/tapTestReport/

can you check if it is flaky?

**Pull request merged**
