### PR TITLE
test: remove fixed tests

### PR DESCRIPTION
**Pull request by kfarnung**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Affected core subsystem(s)

test

### CODE REVIEW

**Review by MSLaguana — APPROVED** [review]
LGTM, I assume the one that was added was failing and had just been missed before?

**Comment by kfarnung** [comment]
The added one is marked flaky upstream and from the looks of the failure is very V8-specific.

**EDIT:**  Here's the entry from the log without the skip:

```
not ok 1206 parallel/test-postmortem-metadata # TODO : Fix flaky test
  ---
  duration_ms: 0.720
  severity: flaky
  stack: |-
    assert.js:76
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Missing constants: v8dbg_bit_field3_dictionary_map_shift,v8dbg_bit_field3_number_of_own_descriptors_shift,v8dbg_class_Code__instruction_size__int,v8dbg_class_Code__instruction_start__uintptr_t,v8dbg_class_ConsString__first__String,v8dbg_class_ConsString__second__String,v8dbg_class_FixedArray__data__uintptr_t,v8dbg_class_FixedArrayBase__length__SMI,v8dbg_class_FixedTypedArrayBase__base_pointer__Object,v8dbg_class_FixedTypedArrayBase__external_pointer__Object,v8dbg_class_HeapNumber__value__double,v8dbg_class_HeapObject__map__Map,v8dbg_class_JSArray__length__Object,v8dbg_class_JSArrayBuffer__backing_store__Object,v8dbg_class_JSArrayBuffer__byte_length__Object,v8dbg_class_JSArrayBufferView__buffer__Object,v8dbg_class_JSArrayBufferView__raw_byte_length__Object,v8dbg_class_JSArrayBufferView__raw_byte_offset__Object,v8dbg_class_JSDate__value__Object,v8dbg_class_JSFunction__context__Context,v8dbg_class_JSFunction__shared__SharedFunctionInfo,v8dbg_class_JSObject__elements__Object,v8dbg_class_JSObject__internal_fields__uintptr_t,v8dbg_class_JSReceiver__raw_properties_or_hash__Object,v8dbg_class_JSRegExp__source__Object,v8dbg_class_Map__bit_field3__int,v8dbg_class_Map__constructor_or_backpointer__Object,v8dbg_class_Map__inobject_properties_start_or_constructor_function_index__char,v8dbg_class_Map__instance_type__uint16_t,v8dbg_class_Map__instance_descriptors__DescriptorArray,v8dbg_class_Map__instance_size_in_words__char,v8dbg_class_Oddball__kind_offset__int,v8dbg_class_Script__line_ends__Object,v8dbg_class_Script__line_offset__SMI,v8dbg_class_Script__name__Object,v8dbg_class_Script__source__Object,v8dbg_class_SeqOneByteString__chars__char,v8dbg_class_SeqTwoByteString__chars__char,v8dbg_class_SharedFunctionInfo__code__Code,v8dbg_class_SharedFunctionInfo__compiler_hints__int,v8dbg_class_SharedFunctionInfo__end_position__int,v8dbg_class_SharedFunctionInfo__function_identifier__Object,v8dbg_class_SharedFunctionInfo__internal_formal_parameter_count__int,v8dbg_class_SharedFunctionInfo__raw_name__Object,v8dbg_class_SharedFunctionInfo__scope_info__ScopeInfo,v8dbg_class_SharedFunctionInfo__script__Object,v8dbg_class_SharedFunctionInfo__start_position_and_type__int,v8dbg_class_SlicedString__offset__SMI,v8dbg_class_SlicedString__parent__String,v8dbg_class_String__length__SMI,v8dbg_class_ThinString__actual__String,v8dbg_context_idx_closure,v8dbg_context_idx_prev,v8dbg_context_min_slots,v8dbg_frametype_ArgumentsAdaptorFrame,v8dbg_frametype_ConstructEntryFrame,v8dbg_frametype_ConstructFrame,v8dbg_frametype_EntryFrame,v8dbg_frametype_ExitFrame,v8dbg_frametype_InternalFrame,v8dbg_frametype_OptimizedFrame,v8dbg_frametype_StubFrame,v8dbg_jsarray_buffer_was_neutered_mask,v8dbg_jsarray_buffer_was_neutered_shift,v8dbg_namedictionary_prefix_start_index,v8dbg_namedictionaryshape_entry_size,v8dbg_namedictionaryshape_prefix_size,v8dbg_off_fp_args,v8dbg_off_fp_context,v8dbg_off_fp_function,v8dbg_prop_attributes_mask,v8dbg_prop_attributes_shift,v8dbg_prop_attributes_DONT_ENUM,v8dbg_prop_attributes_DONT_ENUM,v8dbg_prop_attributes_NONE,v8dbg_prop_attributes_READ_ONLY,v8dbg_prop_desc_details,v8dbg_prop_desc_key,v8dbg_prop_desc_size,v8dbg_prop_desc_value,v8dbg_prop_idx_first,v8dbg_prop_index_mask,v8dbg_prop_index_shift,v8dbg_prop_kind_mask,v8dbg_prop_kind_Accessor,v8dbg_prop_kind_Data,v8dbg_prop_location_mask,v8dbg_prop_location_shift,v8dbg_prop_location_Descriptor,v8dbg_prop_location_Field,v8dbg_prop_representation_double,v8dbg_prop_representation_mask,v8dbg_prop_representation_shift,v8dbg_scopeinfo_idx_first_vars,v8dbg_scopeinfo_idx_ncontextlocals,v8dbg_scopeinfo_idx_nparams,v8dbg_scopeinfo_idx_nstacklocals,v8dbg_sharedfunctioninfo_start_position_mask,v8dbg_sharedfunctioninfo_start_position_shift,v8dbg_type_Code__CODE_TYPE,v8dbg_type_FixedArray__FIXED_ARRAY_TYPE,v8dbg_type_HeapNumber__HEAP_NUMBER_TYPE,v8dbg_type_JSArray__JS_ARRAY_TYPE,v8dbg_type_JSArrayBuffer__JS_ARRAY_BUFFER_TYPE,v8dbg_type_JSDate__JS_DATE_TYPE,v8dbg_type_JSFunction__JS_FUNCTION_TYPE,v8dbg_type_JSGlobalObject__JS_GLOBAL_OBJECT_TYPE,v8dbg_type_JSGlobalProxy__JS_GLOBAL_PROXY_TYPE,v8dbg_type_JSObject__JS_OBJECT_TYPE,v8dbg_type_JSRegExp__JS_REGEXP_TYPE,v8dbg_type_JSTypedArray__JS_TYPED_ARRAY_TYPE,v8dbg_type_Map__MAP_TYPE,v8dbg_type_Oddball__ODDBALL_TYPE,v8dbg_type_Script__SCRIPT_TYPE,v8dbg_type_SharedFunctionInfo__SHARED_FUNCTION_INFO_TYPE,v8dbg_APIObjectType,v8dbg_ConsStringTag,v8dbg_ExternalStringTag,v8dbg_FirstNonstringType,v8dbg_HeapObjectTag,v8dbg_HeapObjectTagMask,v8dbg_OddballException,v8dbg_OddballFalse,v8dbg_OddballNull,v8dbg_OddballTheHole,v8dbg_OddballTrue,v8dbg_OddballUndefined,v8dbg_OddballUninitialized,v8dbg_OneByteStringTag,v8dbg_PointerSizeLog2,v8dbg_SeqStringTag,v8dbg_SlicedStringTag,v8dbg_SmiShiftSize,v8dbg_SmiTag,v8dbg_SmiTagMask,v8dbg_SpecialAPIObjectType,v8dbg_StringEncodingMask,v8dbg_StringRepresentationMask,v8dbg_ThinStringTag,v8dbg_TwoByteStringTag
       at Anonymous function (/Users/iojs/build/workspace/chakracore-test-osx/nodes/osx1010/test/parallel/test-postmortem-metadata.js:43:1)
       at Module.prototype._compile (module.js:666:5)
       at Module._extensions[.js] (module.js:677:3)
       at Module.prototype.load (module.js:577:3)
       at tryModuleLoad (module.js:517:5)
       at Module._load (module.js:509:3)
       at Module.runMain (module.js:707:3)
  ...
```

**Review by jackhorton — APPROVED** [review]
Sorry for the typo. :shipit:

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/208/

**Pull request merged**
