### PR TITLE
chakrashim: fixing lint issue

### PR DESCRIPTION
**Pull request by kfarnung**
Using `reinterpret_cast` instead of a C-style cast.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

chakrashim

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/126/

**Comment by MSLaguana** [comment]
Can't this be a `static_cast`?

**Comment by kfarnung** [comment]
@MSLaguana 

```
  v8string.cc
src\v8string.cc(105): error C2440: 'static_cast': cannot convert from 'uint8_t *' to 'char *' [E:\GitHub\node-chakracore\deps\chakrashim\chakrashim.vcxproj]
  src\v8string.cc(105): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
src\v8string.cc(106): error C2660: 'JsCopyStringOneByte': function does not take 4 arguments [E:\GitHub\node-chakracore\deps\chakrashim\chakrashim.vcxproj]
```

**Comment by kunalspathak** [comment]
yes, I think `reinterpret_cast` make sense because your source type and target type is different and can't do implicit conversion.

**Review by MSLaguana — APPROVED** [review]

**Pull request merged**
