### PR TITLE
tools,doc: apilinks should handle root scenarios

### PR DESCRIPTION
**Pull request by kfarnung**
* Prevent crash when setting root properties
* Allow return outside of function

This is a cherry-pick of https://github.com/nodejs/node/pull/22721 which I'm in the process of landing upstream.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Review by addaleax — APPROVED** [review]
LGTM

Can this be upstreamed (with `tools,doc:` as the prefix)?

**Review by digitalinfinity — APPROVED** [review]

**Comment by kfarnung** [comment]
Thanks @addaleax, fixed the title upstream: https://github.com/nodejs/node/pull/22721

EDIT:  I had forgotten to link this initially, sorry about that!

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/310/

**Comment by kfarnung** [comment]
CI re-run: https://ci.nodejs.org/job/chakracore-test-pull-request/311/

**Comment by kfarnung** [comment]
Seeing consistent, but unrelated macOS failures, opened #590 to track.

**Pull request closed without merging**
