### PR TITLE
chakrashim: ChakraCore release/1.9@c6ae7416fb

### PR DESCRIPTION
**Pull request by kfarnung**
##### Checklist

- [ ] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

chakrashim

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/182/

**Review by MSLaguana — APPROVED** [review]
LGTM if the CI is happy

**Comment by kfarnung** [comment]
Re-run macOS CI: https://ci.nodejs.org/job/chakracore-test-osx/226/

**Review by digitalinfinity — APPROVED** [review]
Rubber stamp LGTM

**Review by boingoing — APPROVED** [review]
👍

**Pull request merged**
