### PR TITLE
Show JS exception details for FATAL ERROR message

### PR DESCRIPTION
**Pull request by obastemur**
If ChakraShim fails to initialize, there is no clear information on what is going on. This happened with the latest Windows update.

Suggested change shows the details of JS exception (if any)

### CODE REVIEW

**Comment by kunalspathak** [comment]
Thanks for addressing this @obastemur . In addition to this issue, there are other known issues with chakra version of node0.12 working with Windows 10.10586. We will be updating the sources with node6.0 that should work with this version of Windows and address these issues.

**Comment by obastemur** [comment]
@kunalspathak I sent these three PRs since there is no node-ch version is actually working on any updated Windows.  These are some of the things I've done to make JXcore(Chakra) working on Windows UWP again. 

I wasn't expecting this much behavior change in Chakra native API since it's shipped with OS. I do understand the JS engine is evolving over time but also expect that the C API is behaving similarly. My naive hope is that the breaking changes in Chakra native API was limited to this Windows update or you release the source codes for Chakra before it breaks again on next Windows update. 

Otherwise it will be hard to ship any UWP/UWA app with either JXcore or node-ch.

**Comment by kunalspathak** [comment]
@obastemur , Thanks for submitting the PRs. There were known issues with node0.12 with chakra.dll shipped with Windows update. We will be soon publishing our node6.0 version in "chnext" that works with latest chakra.dll shipped and addresses the issue in #3 . 
I have merged #2 and #3 in "ch0.12" branch which is based on node0.12. I am reviewing #2 and #3 if that should go in "chnext" as well.

**Comment by kunalspathak** [comment]
Merged 5bee568fc2d9f45a1e64ed92cc28c2b8a5ff8a34 in "ch0.12"

**Comment by jianchun** [comment]
@obastemur Thanks for your fixes! We got delayed by schedule changes and we are pushing updated node-ch today.

Just to clarify, the behavior change you addressed with PR #3 was actually from JS spec, not the Chakra API itself. We'll certainly take note and be very careful to keep Chakra APIs stable. (The other 2 PRs are not behavior change related.)

**Comment by obastemur** [comment]
@kunalspathak thanks for the details.

> @obastemur Thanks for your fixes! We got delayed by schedule changes and we are pushing updated node-ch today.

@jianchun good to hear that. 

> Just to clarify, the behavior change you addressed with PR #3 was actually from JS spec, not the Chakra API itself. We'll certainly take note and be very careful to keep Chakra APIs stable. (The other 2 PRs are not behavior change related.)

Actually #1 is a Chakra API change. Same call on previous Chakra works as expected.

Besides, i.e.

```
  JsValueRef args[] = { nullptr, target };
  JsErrorCode error = JsConstructObject(hostRef, args, _countof(args), result);
```

Consider `hostRef` as a constructor on top of global, this won't work with the new Chakra.dll. (instead of `nullptr`, we should reference 'this' object)  However it works with the pre-update Chakra.

IMHO, these are all expected changes from a JS engine. However it's hard to provide a `node` like solution when you are not able to lock the JS engine version.

**Comment by jianchun** [comment]
@obastemur We are not aware of the issue in #1. I'll try to repro without your fix; please let us know in thread #1 if you have more details.

Yes, the JsConstructObject/JsCallFunction arguments requirement hardening is a breaking change that we took after evaluating all options. The previous loose requirement was leading to inconsistency and crashes. Apologize for any inconvenience.

**Comment by kunalspathak** [comment]
Included the change in c8385b056021439c6a2d241c316c0d055377f120. Closing this PR.

**Pull request closed without merging**
