### PR TITLE
fix --v8-options not working

### PR DESCRIPTION
**Pull request by chopdown**
https://github.com/nodejs/node-chakracore/issues/612

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Review by kfarnung — APPROVED** [review]
LGTM

**Comment by kfarnung** [comment]
@boingoing Please take a look when you have a moment.

**Comment by kfarnung** [comment]
@chopdown Thanks for patching this!

**Comment by boingoing** [comment]
Looks good to me, thanks for the fix.

**Comment by boingoing** [comment]
Landed in d5bf883acfcf21b436e17018cd19555decad0597

**Comment by boingoing** [comment]
Thanks again for the fix, it should be included in the next node-chakracore release.

**Pull request closed without merging**
