### PR TITLE
Update to ChakraCore release/2.0-pre branch

### PR DESCRIPTION
**Pull request by digitalinfinity**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test nosign` (Windows) passes
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)
chakrashim

##### Description of change
Updates chakracore to Microsoft/ChakraCore@35226c9
Made a small change to ChakraCore to change order of cleanup on process shutdown

### CODE REVIEW

**Comment by digitalinfinity** [comment]
@agarwal-sandeep @kunalspathak @boingoing @mrkmarron can a couple of you please review?

**Comment by kunalspathak** [comment]
Can you limit commit title of 228dbe6  to 50 characters? Otherwise LGTM.

**Comment by digitalinfinity** [comment]
Thanks Kunal! Yeah, I'll update when I amend the commits post CR. Should I squash these two to a single commit or is it ok to have two commits here?

**Comment by kunalspathak** [comment]
> is it ok to have two commits here

It is ok to have 2 commits as they both are logically different from each other.

**Comment by digitalinfinity** [comment]
Cool, thanks @kunalspathak - updated the PR, and amended the commit descriptions to follow the template. Also took in one additional chakracore fix from @mrkmarron.

**Comment by mrkmarron** [comment]
LGTM

**Pull request merged**
