### PR TITLE
Inspector support for chakrashim

### PR DESCRIPTION
**Pull request by kfarnung**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-guidelines)

##### Affected core subsystem(s)

inspector, chakrashim

### CODE REVIEW

**Comment by kfarnung** [comment]
CI:  https://ci.nodejs.org/job/chakracore-test-pull-request/8/

Verified that the Linux CI failure is a known issue.  The build and tests succeeded.

**Comment by kfarnung** [comment]
@digitalinfinity Did you have any other feedback for this PR?

**Review by digitalinfinity — APPROVED** [review]
LGTM- thanks for getting this done! Please squash into logical commits again before merging

**Comment by kfarnung** [comment]
@digitalinfinity Thanks!

Final CI:  https://ci.nodejs.org/job/chakracore-test-pull-request/10/

The Linux tests still have the one failure, but that's known.

**Comment by kfarnung** [comment]
Landed as https://github.com/nodejs/node-chakracore/pull/210/commits/3d40cc1cd53c6c3184e37ee6e942fbb945bd837d and https://github.com/nodejs/node-chakracore/pull/210/commits/a043cb86fec8e6f62af1460cbdb2113ecb75b771

**Pull request merged**
