### PR TITLE
test: update .gitignore with .DS_Store for macOS

### PR DESCRIPTION
**Pull request by tommyZZM**
##### Checklist

- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)
no

fix flowing not Untracked files message on git status
```bash
node-chakracore$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed

        .DS_Store
	chakrashim/.DS_Store
	npm/.DS_Store
	openssl/.DS_Store
	openssl/openssl/.DS_Store
	v8/.DS_Store
	v8/test/.DS_Store
	v8/test/mjsunit/.DS_Store
	../tools/eslint/.DS_Store
	../tools/eslint/node_modules/.DS_Store
```

### CODE REVIEW

**Comment by kfarnung** [comment]
@tommyZZM Thanks for your contribution!  I'm wondering if this is something that would be good to do upstream in nodejs/node and then it will merge into here.

/cc @kunalspathak

**Comment by kunalspathak** [comment]
I agree with @kfarnung . This should be made in upstream first.

**Comment by kfarnung** [comment]
Created an upstream PR using @tommyZZM change.

https://github.com/nodejs/node/pull/14721

**Comment by kfarnung** [comment]
@tommyZZM, please continue the discussion over at https://github.com/nodejs/node/pull/14721.

**Pull request closed without merging**
