### PR TITLE
build,lib,test: fix merge issues

### PR DESCRIPTION
**Pull request by kfarnung**
* Since node-chakracore doesn't build MSI packages, it needs to go to
  upload directly in cases where MSI isn't being built. This was
  regressed in a recent merge commit.
* Fixed missing `util` object in `main_thread_only.js`
* Fixed line length issue in `per_thread.js`
* Mark `test-net-bytes-per-incoming-chunk-overhead` flaky on Windows

Refs: https://github.com/nodejs/node-chakracore/commit/8f9f599c7f12eab300ebea74e251a5a05b75fd5e
Refs: https://github.com/nodejs/node-chakracore/commit/f6c6aa276abcda9673d6f2f72074fe9a546125b8

The last successful nightly upload for Windows was [v11.0.0-nightly2018061364643e6292](https://nodejs.org/download/chakracore-nightly/v11.0.0-nightly2018061364643e6292/).

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/274/

**Comment by MSLaguana** [comment]
Is this broken upstream as well if they don't build MSIs? Or is this a chakracore only thing?

**Comment by kfarnung** [comment]
Fixed lint issues and rerun: https://ci.nodejs.org/job/node-test-linter/20312/

**Comment by kfarnung** [comment]
AFAICT they always build MSIs if they are publishing a release.  Since MSIs only allow one install per machine we decided not to publish them.  Arguably this fix could be taken upstream, but I don't know that it's worth it.

**Review by MSLaguana — APPROVED** [review]

**Comment by joaocgreis** [comment]
LGTM. Upstream is good, `upload` can only run if there is a MSI, but here `upload` was modified.

**Pull request merged**
