### PR TITLE
src,test: stub out bigint

### PR DESCRIPTION
**Pull request by kfarnung**
Stubbed out the functions to return `napi_ok` since there's no
`napi_not_implemented` which would be better.

Fixed a couple of lint issues in tests

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by kfarnung** [comment]
@mhdawson @gabrielschulhof Would it make sense to add a status code for `Not implemented`?

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/294/

**Comment by MSLaguana** [comment]
Instead of `napi_ok`, perhaps go with `napi_bigint_expected` since we know we won't ever have an actual bigint, at least until we support them.

**Review by MSLaguana — APPROVED** [review]

**Review by sethbrenith — APPROVED** [review]

**Comment by kfarnung** [comment]
I'm going to land this with napi_ok and come back to it.

**Pull request merged**
