### PR TITLE
Sync to nodejs/master (07-27-2016) 

### PR DESCRIPTION
**Pull request by kunalspathak**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test nosign` (Windows) passes
- [x] commit message follows commit guidelines
##### Affected core subsystem(s)

core
##### Description of change

Sync nodejs/master at 2554549ab5410745c4312a3b039e31e1620e05ab as of 201-07-27

### CODE REVIEW

**Comment by kunalspathak** [comment]
FYI - @nodejs/node-chakracore

**Comment by thefourtheye** [comment]
No additional changes to review. So LGTM if CI is happy. ~~https://ci.nodejs.org/job/node-test-pull-request/3435/~~

Edit: The old CI Run failed because it tried to rebase with the latest master. New CI Run, without rebasing: https://ci.nodejs.org/job/node-test-pull-request/3440/

**Comment by kunalspathak** [comment]
Thanks @thefourtheye !

**Comment by jianchun** [comment]
@thefourtheye How does the CI work? Is it created manually, and do we have permissions to do it? Or can it be configured to run automatically with every PR and log the status directly to the PR?

Seems ran into a rebase merge error.

**Comment by thefourtheye** [comment]
@jianchun I saw that error and created a new CI job without rebasing :-) We have to manually create the CI jobs, as we don't use any hooks. @nodejs/build would be able to shed more light on this.

**Comment by kunalspathak** [comment]
@thefourtheye , seems there are [3 unit test failures](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1010/4321/tapTestReport/) on osx. Are they known issue? I will anyway start investigating on my end, but just wanted to confirm.

**Comment by kunalspathak** [comment]
@thefourtheye , so seems they were legitimate unit test failure that I fixed in ddf08dfe58587fcc203fb643566f340afcfcabb5. Do you mind creating a new CI job for it?

cc - @nodejs/build in case, someone in the group can spawn a new job.

**Comment by jianchun** [comment]
Fix LGTM

**Comment by jianchun** [comment]
lint fixes LGTM

**Comment by kunalspathak** [comment]
Triggered CI https://ci.nodejs.org/job/node-test-commit/4327/ on Friday multiple times and i see timeout in [node-test-commit-freebsd](https://ci.nodejs.org/job/node-test-commit-freebsd/3506/nodes=freebsd10-64/tapTestReport/). For now, I will go ahead and push the commit.

**Comment by thefourtheye** [comment]
@kunalspathak Sorry man. Didn't have access to my laptop for the past few days.

**Pull request merged**
