### PR TITLE
Merge nodejs/master as of 3/14/2017

### PR DESCRIPTION
**Pull request by kunalspathak**
Merge https://github.com/nodejs/node/commit/7acc482432c7b961a52a4a081a87b05f882cf1dd as of 2017-03-14

Interesting commits to review
* 97f22aab95086cd0e9a94f150be6d0d79077c3df = Jslint error fixes
* 9015d47cc1af5df0f0e7f8ea904e329f374ea95e = Skipped few test cases

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

core

### CODE REVIEW

**Comment by kunalspathak** [comment]
CI - https://ci.nodejs.org/job/chakracore-test-windows/40/

@digitalinfinity  - Please review.

**Comment by kunalspathak** [comment]
Another CI - https://ci.nodejs.org/job/chakracore-test-windows/41/

**Comment by digitalinfinity** [comment]
LGTM - I reviewed just the most recent commits and they look fine. Do we have an issue to audit the unit tests that node-chakracore skips?

**Comment by kunalspathak** [comment]
> Do we have an issue to audit the unit tests that node-chakracore skips?

Not really because it was implicit before we merge . 😄 But officially, i have opened https://github.com/nodejs/node-chakracore/issues/188

**Pull request merged**
