### PR TITLE
Force indexed set option for Array

### PR DESCRIPTION
**Pull request by obastemur**
V8 allows defining an indexed item using v8::Integer/v8::Number as key. However chakrart::JsSetProperty fails if the host object is an Array.
Proposed change checks the data type for `key` and uses JsSetIndexedProperty option instead (for Array host).

### CODE REVIEW

**Comment by kunalspathak** [comment]
@obastemur , could you give a short repro or error that you get when you use `v8::Number/v8::Integer` as key with `chakrart::JsSetProperty`. We didn't change the API behavior, so it should work post Windows update. It will help us identify some underlying issue that is causing the break.

**Comment by jianchun** [comment]
Investigated and found a bug in GetPropertyIdFromValue (jsrtuitils.cc) which handles indexed properties incorrectly. Working on a fix.

**Comment by jianchun** [comment]
@obastemur I have committed 18d118e9d30fd99ce0c0363256f49faa2f5c33fe which should fix this issue. We did it that way to optimize Object::Get/Set for string keys. We'll reevaluate your fix if we find needs to optimize differently. Thanks!

**Comment by obastemur** [comment]
@jianchun thats great. Closing this then. BTW; Would you consider hosting `Chakrashim` under it's own repository ? It could be much easier to collaborate / target as a submodule etc.

**Comment by jianchun** [comment]
@obastemur Thanks!

> Would you consider hosting Chakrashim under it's own repository ? It could be much easier to collaborate / target as a submodule etc.

@orangemocha suggested this as well. We will consider once we sort out other logistics.

**Pull request closed without merging**
