### PR TITLE
10.6.0 proposal

### PR DESCRIPTION
**Pull request by kfarnung**
##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: ~~https://ci.nodejs.org/job/chakracore-test-pull-request/282/~~ https://ci.nodejs.org/job/chakracore-test-pull-request/283/

**Review by boingoing — APPROVED** [review]
Looks ok to me. If CI passes, let's go 👍

**Comment by kfarnung** [comment]
One more attempt at CI: https://ci.nodejs.org/job/chakracore-test-pull-request/284/

**Review by MSLaguana — APPROVED** [review]
LGTM. Do you plan on bringing over the chakracore 1.10 changes as well?

**Comment by kfarnung** [comment]
CI looks good:  https://ci.nodejs.org/job/chakracore-test-pull-request/284/

**Comment by kfarnung** [comment]
Once cc-1.10 lands and is deemed stable I'll pull that over.

**Pull request merged**
