### PR TITLE
Update node-chakracore with nodejs/master changes

### PR DESCRIPTION
**Pull request by kunalspathak**
This PR updates node-chakracore with 7406cd3a59302d50420e3c6c12359ac20094ad24 of nodejs/node "master" branch. All the commits, except last 3 commits are from nodejs/node repo and are present to retain the history. 
Summary of last 3 commits are as follows:
- chakrashim changes - After nodejs/node merge, there were several new v8 APIs that were not implemented in chakrashim. This commit close that gap and implements those APIs in chakrashim.
- unit test changes - Fixed several unit test with right error message to make them work on node with chakracore. Also there are some unit test that are v8 specific, so disabled them from running if on chakracore.
- update to chakracore - Updated chakracore to 1.1.0.3. This includes some bug fixes. See Microsoft/Chakracore's [release/1.1](https://github.com/Microsoft/ChakraCore/commits/release/1.1) branch for more details.

### CODE REVIEW

**Comment by kunalspathak** [comment]
@nodejs/chakra , @nodejs/node-chakracore  - FYI.

**Comment by thefourtheye** [comment]
Rubberstamp LGTM. Let's see if the CI is working for this PR https://ci.nodejs.org/job/node-test-pull-request/1686/ cc @nodejs/ci

**Comment by orangemocha** [comment]
Two test failures on ARM.
- https://ci.nodejs.org/job/node-test-binary-arm/1112/RUN_SUBSET=3,nodes=pi2-raspbian-wheezy/tapTestReport/
- https://ci.nodejs.org/job/node-test-binary-arm/1112/RUN_SUBSET=4,nodes=pi2-raspbian-wheezy/tapTestReport/

The first was supposed to be marked as flaky in master (https://github.com/nodejs/node/pull/4765#issuecomment-181996804). We should check if that change has made it here.

The second one is new. @nodejs/testing is that another flaky test?

**Comment by Trott** [comment]
The first one was re-marked flaky in master a few hours ago, so nothing to worry about there.

The second one `test-process-getactivehandles` is not one I recall seeing before.

**Comment by orangemocha** [comment]
A [second CI run](https://ci.nodejs.org/job/node-test-binary-arm/1125/) shows two failures on ARM:
- test-child-process-fork-regr-gh-2847.js
- test-http-regr-gh-2928.js

**Comment by santigimeno** [comment]
Can somebody copy the errors? Thanks

**Comment by orangemocha** [comment]
From the first run:

```
not ok 90 test-process-getactivehandles.js
# TIMEOUT
```

I am doing a stress run on this one.

From the second run:

```
not ok 7 test-child-process-fork-regr-gh-2847.js
# TIMEOUT
```

**Comment by santigimeno** [comment]
@orangemocha Not completely sure, but it looks like this commit https://github.com/nodejs/node/commit/4e4b260b07dc2519aa5333b82e8f8a4aac861027 fixing the `test-child-process-fork-regr-gh-2847.js` could be missing.

**Comment by orangemocha** [comment]
test-process-getactivehandles is flaky on nodejs/node:master :(

https://ci.nodejs.org/job/node-stress-single-test/504/nodes=pi2-raspbian-wheezy/console

**Comment by orangemocha** [comment]
@santigimeno you are right, this PR is only including changes from master up to https://github.com/nodejs/node-chakracore/commit/7406cd3a59302d50420e3c6c12359ac20094ad24, so the fix for those flaky tests are missing.

I'll follow up on test-process-getactivehandles in nodejs/node.

LGTM

**Comment by kunalspathak** [comment]
Thanks @orangemocha , @thefourtheye for review.

**Comment by kunalspathak** [comment]
Updated the commits with metadata information.

**Comment by thefourtheye** [comment]
Merge commits are not preferred. Can you get rid off them?

**Comment by orangemocha** [comment]
> Merge commits are not preferred. Can you get rid off them?

@thefourtheye Not sure if there's an easy way to do that. It would involve cherry picking each commit from nodejs/node:master, which would be laborious and error-prone.

We did use merge commits in Core for a long time, until recently we changed to cherry-picking commits from master to the LTS branches. It's easier there because LTS branches hardly ever have changes of their own.

**Comment by kunalspathak** [comment]
Agree with @orangemocha . With rebase we will lose the original commit hashes and we won't be able to follow branches in which commits propagated.

**Comment by thefourtheye** [comment]
That's true. Hmmm, how about this? Going forward, we can probably have syncing(merging) with node/master as a separate PR, which can have merge commits. But other PRs can be landed manually like we do in nodejs core (with the similar commit log modifications, like PR-URL and Reviewed-By). Will that be okay?

**Comment by orangemocha** [comment]
Yep. And the net effect of this PR is what you describe (I think). There is one merge commit and then a few node-chakracore specific changes, including deps updates, and the commits that are not from master have the standard commit metadata.

The engine updates might however be necessary with the same PR as the integration from master, or otherwise chakracore-master might be broken.

**Comment by kunalspathak** [comment]
> we can probably have syncing(merging) with node/master as a separate PR,

The problem with that is there could be v8 API changes that needs equivalent chakrashim changes to build node+chakracore. If we don't submit a single commit for that (merge + chakrashim) changes then a head that just has nodejs merge will be useless because it won't build. This PR address that by having node changes merged followed by chakrashim, core changes in 2 separate commits.

**Comment by thefourtheye** [comment]
> The engine updates might however be necessary with the same PR as the integration from master, or otherwise chakracore-master might be broken.
> 
> The problem with that is there could be v8 API changes that needs equivalent chakrashim changes to build node+chakracore. If we don't submit a single commit for that (merge + chakrashim) changes then a head that just has nodejs merge will be useless because it won't build.

Makes perfect sense. Thanks @orangemocha & @kunalspathak for helping me understand :-)

**Comment by thefourtheye** [comment]
@kunalspathak About the commit metadata, we normally update them when landing the changes and the Reviewed-By field has the collaborators who explicitly say that the patch looks okay in the PR. In the commits, I see "Jianchun Xu" and I don't see their approval in the PR. Are we missing something?

**Comment by kunalspathak** [comment]
@thefourtheye , thanks for pointing it out, will remember to update when landing the changes instead of still in PR. "Jianchun Xu" reviewed chakrashim changes in private repo. Should I get sign off from me on this PR or its ok not to include him as a reviewer?

**Comment by thefourtheye** [comment]
@kunalspathak It would be better if we can have explicit sign-offs in all our PRs.

**Comment by kunalspathak** [comment]
@thefourtheye , Sure.

@jianchun , can you please sign off.

**Comment by jianchun** [comment]
> @jianchun , can you please sign off.

I double checked and yes the "Update chakracore to 1.1.0.3" commit is good.

**Comment by jianchun** [comment]
> @jianchun , can you please sign off.

And the other commits LGTM too... I reviewed before. (Sorry clicked too fast).

**Comment by jianchun** [comment]
FYI, I unpacked this PR and noticed an issue, filed https://github.com/nodejs/node/commit/76cb81b354de8447898427619c66c86c59b22b3d#commitcomment-16209618

**Comment by kunalspathak** [comment]
I have already opened an issue at nodejs/node#5094.

Sent from Outlook Mobilehttps://aka.ms/blhgte

On Fri, Feb 19, 2016 at 10:19 AM -0800, "Jianchun Xu" <notifications@github.com<mailto:notifications@github.com>> wrote:

FYI, I unpacked this PR and noticed an issue, filed nodejs/node@76cb81b#commitcomment-16209618https://github.com/nodejs/node/commit/76cb81b354de8447898427619c66c86c59b22b3d#commitcomment-16209618

##

**Comment by jianchun** [comment]
> I have already opened an issue ...

Great!

**Comment by orangemocha** [comment]
Landed in chakracore-master with 1992a831e5fc46c3db25cd6b623b741ea1b65b2c, and fast-forwarded master to 7406cd3a59302d50420e3c6c12359ac20094ad24. Thank you!

**Pull request closed without merging**
