### PR TITLE
buffer,test: remove species workaround

### PR DESCRIPTION
**Pull request by kfarnung**
* Re-enable some tests adding some ChakraCore-specific changes.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/291/

**Review by MSLaguana — APPROVED** [review]

**Comment by kfarnung** [comment]
Linter re-run: https://ci.nodejs.org/job/node-test-linter/20731/

**Review by boingoing — APPROVED** [review]

**Comment by kfarnung** [comment]
Re-enabled a couple of other tests that had their ChakraCore issues fixed and kicked off a new CI:  https://ci.nodejs.org/job/chakracore-test-pull-request/292/

**Comment by MSLaguana** [comment]
LGTM

**Comment by kfarnung** [comment]
Restarted the macOS CI leg: https://ci.nodejs.org/job/chakracore-test-osx/392/

**Comment by kfarnung** [comment]
Fixed some other differences in `test-repl-top-level-await`, hopefully the last CI: https://ci.nodejs.org/job/chakracore-test-pull-request/293/

**Pull request merged**
