### PR TITLE
Updated for node-chakracore-7.0.0-pre10

### PR DESCRIPTION
**Pull request by aruneshchandra**

### CODE REVIEW

**Comment by digitalinfinity** [comment]
LGTM

**Comment by kunalspathak** [comment]
@aruneshchandra , this PR was supposed to be targeted for `xplat` branch and not `chakracore-master`.

**Comment by alexlamsl** [comment]
So... I am currently on `7.0.0-pre9`, is this the build I should use?

I am asking because I don't see any MSIs in the release, and also it seems to be building from a different branch than the previous releases.

Would be nice to finally run `eslint` without modifying its source every time after `npm install` 😅 

(Also, if this is based off nodejs' master branch, shouldn't it be `8.0.0-pre` by now?)

**Comment by kunalspathak** [comment]
@alexlamsl 
> it seems to be building from a different branch than the previous releases.

The branch on which `pre10` is based off is ahead of `chakracore-master` and includes features like debugging and TTD. We will be soon be merging these 2 branches. 

> I don't see any MSIs in the release,

You are right. There are no MSIs in the release but you can follow the instructions on [release](https://github.com/nodejs/node-chakracore/releases/tag/node-chakracore-7.0.0-pre10) page to use `nvs`  that should give you same ability.

> (Also, if this is based off nodejs' master branch, shouldn't it be 8.0.0-pre by now?)

If you see https://github.com/nodejs/node-chakracore/commit/9814c0b1337871728168a16eaf02fca2f6c3d2ed , it is still based on `7.0`.

**Comment by alexlamsl** [comment]
@kunalspathak thanks for the clarification 👍

**Pull request merged**
