### PR TITLE
Merging v8.1.2 into v8.x

### PR DESCRIPTION
**Pull request by kfarnung**
Node released v8.1.2 to address an [issue with their build definition](https://github.com/nodejs/node/issues/13667).  Since it's only a version bump we might as well take it.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

doc,src

### CODE REVIEW

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/89/

**Review by kunalspathak — APPROVED** [review]

**Review by MSLaguana — APPROVED** [review]

**Comment by MSLaguana** [comment]
Looks like the non-windows CI failed, but I believe it's a test that we need to mark as flaky and fix in future:
`not ok 1490 sequential/test-benchmark-net`

**Comment by MSLaguana** [comment]
Actually, OSX build failed because of lingering processes, but we know about that as well.

**Comment by kfarnung** [comment]
@MSLaguana @kunalspathak Thanks!  Those CI failures are known and unrelated.

**Pull request merged**
