### PR TITLE
Update chakracore to 1.7

### PR DESCRIPTION
**Pull request by kunalspathak**
Updated chakracore to https://github.com/Microsoft/ChakraCore/commit/165d3ce8208613ea75403e4e279e02ba40bfcff6

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

chakracore

### CODE REVIEW

**Comment by kunalspathak** [comment]
https://ci.nodejs.org/job/chakracore-test-pull-request/108/

**Review by kfarnung — APPROVED** [review]

**Review by digitalinfinity — APPROVED** [review]

**Comment by kunalspathak** [comment]
win-vcbt2015 failed with below error. I will look into it when i get chance.
```cmd
vcbt2015\deps\chakrashim\core\build\..\bin\ChakraCore\ChakraCore.vcxproj.metaproj" (2) is building "c:\workspace\node-compile-windows\label\win-vcbt2015\deps\chakrashim\core\lib\Common\util\Chakra.Common.Util.vcxproj" (17) on node 6 (default targets).
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(93,27): error MSB4086: A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "".0" instead of a number, in condition "'$(UseOSWinMdReferences)' == '' and ('$(TargetPlatformWinMDLocation)' == '' and '$(TargetPlatformIdentifier)' == 'Windows' and '$(TargetPlatformVersion)' > '7.0')". [c:\workspace\node-compile-windows\label\win-vcbt2015\deps\chakrashim\core\lib\Common\util\Chakra.Common.Util.vcxproj] [c:\workspace\node-compile-windows\label\win-vcbt2015\deps\chakrashim\chakracore.vcxproj]```

**Comment by MSLaguana** [comment]
I just kicked off a CI build of chakracore-master to see if the same issue happened there, and instead hit a different issue entirely in node land: https://ci.nodejs.org/job/node-compile-windows/label=win-vcbt2015/10537/

Could it be some flakiness of the CI instead of a build issue on our end?

**Comment by MSLaguana** [comment]
Ah nevermind, I misread the errors. It is the same issue.

**Comment by MSLaguana** [comment]
I believe that this change is related to the breakage here: https://github.com/Microsoft/ChakraCore/commit/55fcecce87dec5bde51f640aba4ed051b74e9a60

Looks like the CI might not have win10 sdks, or have them in a broken state?

**Comment by kunalspathak** [comment]
Yes that is the commit which modified those `props` file. But I didn't get chance to investigate further. If you have time, feel free to send PR in `Microsoft/chakracore` to address this.

**Comment by MSLaguana** [comment]
Found the issue, a fix is at https://github.com/Microsoft/ChakraCore/pull/3386

**Comment by MSLaguana** [comment]
If you update this PR to use the latest from the `release/1.7` branch I believe it should work now.

**Comment by kfarnung** [comment]
@kunalspathak I'm currently rebasing this PR, updating to the latest 1.7, and running the local build/tests.  I'll just push to this PR, if possible, once that's all done.

**Comment by kfarnung** [comment]
Rebased, updated, and new CI: https://ci.nodejs.org/job/chakracore-test-pull-request/119/

**Pull request merged**
